### ISSUE TITLE
error running train_vae.py and train_classifier.py

### ISSUE THREAD

**Issue by mehdimo** [saemundsson/semisupervised_vae#1]
Hello,

Trying to run the program, I face the following error:
I am using tensorflow v 0.12.0-rc1. before that when I was on version 0.11, I got another error as indicated [here](https://github.com/tensorflow/models/issues/742).

The message for the current error is:

`WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/prettytensor/bookkeeper.py:258 in add_histogram_summary.: histogram_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.histogram. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on their scope.
WARNING:tensorflow:From /home/mdh/semisupervised_vae/vae.py:158 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "train_vae.py", line 51, in <module>
    learning_rate = learning_rate, seed = seed, stop_iter = 30, print_every = 10, draw_img = 0 )
  File "/home/mdh/semisupervised_vae/vae.py", line 206, in train
    self.saver.save( sess, self.save_path )
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1314, in save
    "Parent directory of {} doesn't exist, can't save.".format(save_path))
ValueError: Parent directory of checkpoints/model_VAE_0.0003-50_1481835936.26.cpkt doesn't exist, can't save.
`

**Comment by mehdimo** [comment]
Actually I found out that the problem is 'checkpoints' folder that is missing in the repository. By creating this folder in the project, the program continues to work.
